example.property: "I AM THE DEFAULT"
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://scy.pub:3306/eagle_eye_local
    username: root
    password: 123456

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
redis.server: "redis"
redis.port: "6379"
signing.key: "345345fsdfsf5345"
